#!/bin/bash

if [[ -z "$MASTER" ]]; then
    MASTER="local[*]"
fi

if [[ "$1" == "debug" ]]; then
    export SPARK_SUBMIT_OPTS="-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=5005"
    if [[ "$2" == "executor" ]]; then
        ./spark stop
        MASTER="local[1]"
    fi
fi

$SPARK_HOME/bin/spark-submit --class "SimpleApp" --master $MASTER $HOME/personal/scala-projects/spark-examples/target/scala-2.13/spark-examples_2.13-0.1.0-SNAPSHOT.jar
