#!/bin/bash

export SPARK_WORKER_INSTANCES=8
export SPARK_WORKER_CORES=1
export SPARK_MASTER_HOST=localhost

if [[ "$1" != "start" ]];
then
    $SPARK_HOME/sbin/stop-worker.sh
    $SPARK_HOME/sbin/stop-master.sh
fi

if [[ $1 == "stop" ]];
then
    exit 0
fi

$SPARK_HOME/sbin/start-master.sh

$SPARK_HOME/sbin/start-worker.sh --cores $SPARK_WORKER_CORES spark://localhost:7077
